# SonarQube Project Configuration
sonar.projectKey=com.cognizant:codequality
sonar.projectName=01-Code-Quality-SonarQube
sonar.projectVersion=1.0.0

# Path to source directories
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8

# Server url
sonar.host.url=http://localhost:9000
